package com.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_Org", "OrgID", Org.class);
		arp.addMapping("t_Resource", "ResID", Resource.class);
		arp.addMapping("t_Role", "RoleID", Role.class);
		arp.addMapping("t_RoleResource", "AutoID", RoleResource.class);
		arp.addMapping("t_User", "UserID", User.class);
	}
}

