package com.common.model;

import com.common.model.base.BaseResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Resource extends BaseResource<Resource> {
	public static final Resource dao = new Resource();
}
