package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrg<M extends BaseOrg<M>> extends Model<M> implements IBean {

	public void setOrgID(java.lang.Integer OrgID) {
		set("OrgID", OrgID);
	}

	public java.lang.Integer getOrgID() {
		return get("OrgID");
	}

	public void setOrgCode(java.lang.String OrgCode) {
		set("OrgCode", OrgCode);
	}

	public java.lang.String getOrgCode() {
		return get("OrgCode");
	}

	public void setOrgName(java.lang.String OrgName) {
		set("OrgName", OrgName);
	}

	public java.lang.String getOrgName() {
		return get("OrgName");
	}

	public void setParentCode(java.lang.String ParentCode) {
		set("ParentCode", ParentCode);
	}

	public java.lang.String getParentCode() {
		return get("ParentCode");
	}

	public void setOrgGrade(java.lang.Integer OrgGrade) {
		set("OrgGrade", OrgGrade);
	}

	public java.lang.Integer getOrgGrade() {
		return get("OrgGrade");
	}

	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}

	public java.lang.String getRemark() {
		return get("Remark");
	}

}
