package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRoleResource<M extends BaseRoleResource<M>> extends Model<M> implements IBean {

	public void setAutoID(java.lang.Integer AutoID) {
		set("AutoID", AutoID);
	}

	public java.lang.Integer getAutoID() {
		return get("AutoID");
	}

	public void setRoleID(java.lang.Integer RoleID) {
		set("RoleID", RoleID);
	}

	public java.lang.Integer getRoleID() {
		return get("RoleID");
	}

	public void setResID(java.lang.Integer ResID) {
		set("ResID", ResID);
	}

	public java.lang.Integer getResID() {
		return get("ResID");
	}

	public void setPower(java.lang.Integer Power) {
		set("Power", Power);
	}

	public java.lang.Integer getPower() {
		return get("Power");
	}

	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}

	public java.lang.String getRemark() {
		return get("Remark");
	}

}
