package com.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setRoleID(java.lang.Integer RoleID) {
		set("RoleID", RoleID);
	}

	public java.lang.Integer getRoleID() {
		return get("RoleID");
	}

	public void setRoleName(java.lang.String RoleName) {
		set("RoleName", RoleName);
	}

	public java.lang.String getRoleName() {
		return get("RoleName");
	}

	public void setRemark(java.lang.String Remark) {
		set("Remark", Remark);
	}

	public java.lang.String getRemark() {
		return get("Remark");
	}

	public void setCreateTime(java.util.Date CreateTime) {
		set("CreateTime", CreateTime);
	}

	public java.util.Date getCreateTime() {
		return get("CreateTime");
	}

}
